# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stylehub_pb2 as stylehub__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stylehub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CartServiceStub(object):
    """-------------------------------------------------------------------
    1. Cart Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddItem = channel.unary_unary(
                '/stylehub.CartService/AddItem',
                request_serializer=stylehub__pb2.AddItemRequest.SerializeToString,
                response_deserializer=stylehub__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/stylehub.CartService/GetCart',
                request_serializer=stylehub__pb2.GetCartRequest.SerializeToString,
                response_deserializer=stylehub__pb2.Cart.FromString,
                _registered_method=True)
        self.EmptyCart = channel.unary_unary(
                '/stylehub.CartService/EmptyCart',
                request_serializer=stylehub__pb2.EmptyCartRequest.SerializeToString,
                response_deserializer=stylehub__pb2.Empty.FromString,
                _registered_method=True)


class CartServiceServicer(object):
    """-------------------------------------------------------------------
    1. Cart Service
    -------------------------------------------------------------------
    """

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmptyCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=stylehub__pb2.AddItemRequest.FromString,
                    response_serializer=stylehub__pb2.Empty.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=stylehub__pb2.GetCartRequest.FromString,
                    response_serializer=stylehub__pb2.Cart.SerializeToString,
            ),
            'EmptyCart': grpc.unary_unary_rpc_method_handler(
                    servicer.EmptyCart,
                    request_deserializer=stylehub__pb2.EmptyCartRequest.FromString,
                    response_serializer=stylehub__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.CartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.CartService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CartService(object):
    """-------------------------------------------------------------------
    1. Cart Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.CartService/AddItem',
            stylehub__pb2.AddItemRequest.SerializeToString,
            stylehub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.CartService/GetCart',
            stylehub__pb2.GetCartRequest.SerializeToString,
            stylehub__pb2.Cart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmptyCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.CartService/EmptyCart',
            stylehub__pb2.EmptyCartRequest.SerializeToString,
            stylehub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProductCatalogServiceStub(object):
    """-------------------------------------------------------------------
    2. Product Catalog Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProducts = channel.unary_unary(
                '/stylehub.ProductCatalogService/ListProducts',
                request_serializer=stylehub__pb2.Empty.SerializeToString,
                response_deserializer=stylehub__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/stylehub.ProductCatalogService/GetProduct',
                request_serializer=stylehub__pb2.GetProductRequest.SerializeToString,
                response_deserializer=stylehub__pb2.Product.FromString,
                _registered_method=True)
        self.SearchProducts = channel.unary_unary(
                '/stylehub.ProductCatalogService/SearchProducts',
                request_serializer=stylehub__pb2.SearchProductsRequest.SerializeToString,
                response_deserializer=stylehub__pb2.SearchProductsResponse.FromString,
                _registered_method=True)


class ProductCatalogServiceServicer(object):
    """-------------------------------------------------------------------
    2. Product Catalog Service
    -------------------------------------------------------------------
    """

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductCatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=stylehub__pb2.Empty.FromString,
                    response_serializer=stylehub__pb2.ListProductsResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=stylehub__pb2.GetProductRequest.FromString,
                    response_serializer=stylehub__pb2.Product.SerializeToString,
            ),
            'SearchProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProducts,
                    request_deserializer=stylehub__pb2.SearchProductsRequest.FromString,
                    response_serializer=stylehub__pb2.SearchProductsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.ProductCatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.ProductCatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductCatalogService(object):
    """-------------------------------------------------------------------
    2. Product Catalog Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.ProductCatalogService/ListProducts',
            stylehub__pb2.Empty.SerializeToString,
            stylehub__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.ProductCatalogService/GetProduct',
            stylehub__pb2.GetProductRequest.SerializeToString,
            stylehub__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.ProductCatalogService/SearchProducts',
            stylehub__pb2.SearchProductsRequest.SerializeToString,
            stylehub__pb2.SearchProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CurrencyServiceStub(object):
    """-------------------------------------------------------------------
    3. Currency Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupportedCurrencies = channel.unary_unary(
                '/stylehub.CurrencyService/GetSupportedCurrencies',
                request_serializer=stylehub__pb2.Empty.SerializeToString,
                response_deserializer=stylehub__pb2.GetSupportedCurrenciesResponse.FromString,
                _registered_method=True)
        self.Convert = channel.unary_unary(
                '/stylehub.CurrencyService/Convert',
                request_serializer=stylehub__pb2.CurrencyConversionRequest.SerializeToString,
                response_deserializer=stylehub__pb2.Money.FromString,
                _registered_method=True)


class CurrencyServiceServicer(object):
    """-------------------------------------------------------------------
    3. Currency Service
    -------------------------------------------------------------------
    """

    def GetSupportedCurrencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Convert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrencyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSupportedCurrencies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedCurrencies,
                    request_deserializer=stylehub__pb2.Empty.FromString,
                    response_serializer=stylehub__pb2.GetSupportedCurrenciesResponse.SerializeToString,
            ),
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=stylehub__pb2.CurrencyConversionRequest.FromString,
                    response_serializer=stylehub__pb2.Money.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.CurrencyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.CurrencyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CurrencyService(object):
    """-------------------------------------------------------------------
    3. Currency Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def GetSupportedCurrencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.CurrencyService/GetSupportedCurrencies',
            stylehub__pb2.Empty.SerializeToString,
            stylehub__pb2.GetSupportedCurrenciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.CurrencyService/Convert',
            stylehub__pb2.CurrencyConversionRequest.SerializeToString,
            stylehub__pb2.Money.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdServiceStub(object):
    """-------------------------------------------------------------------
    4. Ad Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAds = channel.unary_unary(
                '/stylehub.AdService/GetAds',
                request_serializer=stylehub__pb2.AdRequest.SerializeToString,
                response_deserializer=stylehub__pb2.AdResponse.FromString,
                _registered_method=True)


class AdServiceServicer(object):
    """-------------------------------------------------------------------
    4. Ad Service
    -------------------------------------------------------------------
    """

    def GetAds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAds,
                    request_deserializer=stylehub__pb2.AdRequest.FromString,
                    response_serializer=stylehub__pb2.AdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.AdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.AdService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdService(object):
    """-------------------------------------------------------------------
    4. Ad Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def GetAds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.AdService/GetAds',
            stylehub__pb2.AdRequest.SerializeToString,
            stylehub__pb2.AdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecommendationServiceStub(object):
    """-------------------------------------------------------------------
    5. Recommendation Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRecommendations = channel.unary_unary(
                '/stylehub.RecommendationService/ListRecommendations',
                request_serializer=stylehub__pb2.ListRecommendationsRequest.SerializeToString,
                response_deserializer=stylehub__pb2.ListRecommendationsResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """-------------------------------------------------------------------
    5. Recommendation Service
    -------------------------------------------------------------------
    """

    def ListRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecommendations,
                    request_deserializer=stylehub__pb2.ListRecommendationsRequest.FromString,
                    response_serializer=stylehub__pb2.ListRecommendationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """-------------------------------------------------------------------
    5. Recommendation Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def ListRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.RecommendationService/ListRecommendations',
            stylehub__pb2.ListRecommendationsRequest.SerializeToString,
            stylehub__pb2.ListRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ShippingServiceStub(object):
    """-------------------------------------------------------------------
    6. Shipping Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuote = channel.unary_unary(
                '/stylehub.ShippingService/GetQuote',
                request_serializer=stylehub__pb2.GetQuoteRequest.SerializeToString,
                response_deserializer=stylehub__pb2.GetQuoteResponse.FromString,
                _registered_method=True)
        self.ShipOrder = channel.unary_unary(
                '/stylehub.ShippingService/ShipOrder',
                request_serializer=stylehub__pb2.ShipOrderRequest.SerializeToString,
                response_deserializer=stylehub__pb2.ShipOrderResponse.FromString,
                _registered_method=True)


class ShippingServiceServicer(object):
    """-------------------------------------------------------------------
    6. Shipping Service
    -------------------------------------------------------------------
    """

    def GetQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShipOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShippingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuote,
                    request_deserializer=stylehub__pb2.GetQuoteRequest.FromString,
                    response_serializer=stylehub__pb2.GetQuoteResponse.SerializeToString,
            ),
            'ShipOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ShipOrder,
                    request_deserializer=stylehub__pb2.ShipOrderRequest.FromString,
                    response_serializer=stylehub__pb2.ShipOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.ShippingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.ShippingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShippingService(object):
    """-------------------------------------------------------------------
    6. Shipping Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def GetQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.ShippingService/GetQuote',
            stylehub__pb2.GetQuoteRequest.SerializeToString,
            stylehub__pb2.GetQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShipOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.ShippingService/ShipOrder',
            stylehub__pb2.ShipOrderRequest.SerializeToString,
            stylehub__pb2.ShipOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PaymentServiceStub(object):
    """-------------------------------------------------------------------
    7. Payment Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Charge = channel.unary_unary(
                '/stylehub.PaymentService/Charge',
                request_serializer=stylehub__pb2.ChargeRequest.SerializeToString,
                response_deserializer=stylehub__pb2.ChargeResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """-------------------------------------------------------------------
    7. Payment Service
    -------------------------------------------------------------------
    """

    def Charge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Charge': grpc.unary_unary_rpc_method_handler(
                    servicer.Charge,
                    request_deserializer=stylehub__pb2.ChargeRequest.FromString,
                    response_serializer=stylehub__pb2.ChargeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """-------------------------------------------------------------------
    7. Payment Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def Charge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.PaymentService/Charge',
            stylehub__pb2.ChargeRequest.SerializeToString,
            stylehub__pb2.ChargeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EmailServiceStub(object):
    """-------------------------------------------------------------------
    8. Email Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOrderConfirmation = channel.unary_unary(
                '/stylehub.EmailService/SendOrderConfirmation',
                request_serializer=stylehub__pb2.SendOrderConfirmationRequest.SerializeToString,
                response_deserializer=stylehub__pb2.Empty.FromString,
                _registered_method=True)


class EmailServiceServicer(object):
    """-------------------------------------------------------------------
    8. Email Service
    -------------------------------------------------------------------
    """

    def SendOrderConfirmation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOrderConfirmation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrderConfirmation,
                    request_deserializer=stylehub__pb2.SendOrderConfirmationRequest.FromString,
                    response_serializer=stylehub__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.EmailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.EmailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmailService(object):
    """-------------------------------------------------------------------
    8. Email Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def SendOrderConfirmation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.EmailService/SendOrderConfirmation',
            stylehub__pb2.SendOrderConfirmationRequest.SerializeToString,
            stylehub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CheckoutServiceStub(object):
    """-------------------------------------------------------------------
    9. Checkout Service
    -------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/stylehub.CheckoutService/PlaceOrder',
                request_serializer=stylehub__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=stylehub__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)


class CheckoutServiceServicer(object):
    """-------------------------------------------------------------------
    9. Checkout Service
    -------------------------------------------------------------------
    """

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=stylehub__pb2.PlaceOrderRequest.FromString,
                    response_serializer=stylehub__pb2.PlaceOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stylehub.CheckoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stylehub.CheckoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckoutService(object):
    """-------------------------------------------------------------------
    9. Checkout Service
    -------------------------------------------------------------------
    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stylehub.CheckoutService/PlaceOrder',
            stylehub__pb2.PlaceOrderRequest.SerializeToString,
            stylehub__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
