apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-currency-service
  labels:
    app: {{ .Release.Name }}-currency-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-currency-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.microservices.currency.port }}"
      labels:
        app: {{ .Release.Name }}-currency-service
    spec:
      containers:
        - name: currency-service
          image: "{{ .Values.image.repositoryPrefix }}/currency-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.microservices.currency.port }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.microservices.currency.port }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- if .Values.otel.endpoint }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.endpoint | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.microservices.currency.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-currency-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-currency-service
  ports:
    - port: {{ .Values.microservices.currency.port }}
      targetPort: {{ .Values.microservices.currency.port }}
