apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-email-service
  labels:
    app: {{ .Release.Name }}-email-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-email-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.microservices.email.port }}"
      labels:
        app: {{ .Release.Name }}-email-service
    spec:
      containers:
        - name: email-service
          image: "{{ .Values.image.repositoryPrefix }}/email-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.otel.endpoint }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.endpoint | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.microservices.email.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-email-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-email-service
  ports:
    - port: {{ .Values.microservices.email.port }}
      targetPort: {{ .Values.microservices.email.port }}
